[package]
name = "slint-poker"
version = "0.1.0"
edition = "2021"
authors = ["Poker Demo"]

[dependencies]
slint = "1.14"
rand = "0.8"

[build-dependencies]
slint-build = "1.14"

[profile.release]
opt-level = "s"
